Controllers/DesignationController.cs
using EmployeeManagement.Data;
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Controllers
{
    public class DesignationController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DesignationController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var designations = await _db.Designation.ToListAsync();
            return View(designations);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Designation designation)
        {
            if (ModelState.IsValid)
            {
                _db.Designation.Add(designation);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(designation);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var designation = await _db.Designation.FindAsync(id);
            if (designation == null)
            {
                return NotFound();
            }

            return View(designation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Designation designation)
        {
            if (id != designation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Entry(designation).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(designation);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var designation = await _db.Designation.FindAsync(id);
            if (designation == null)
            {
                return NotFound();
            }

            _db.Designation.Remove(designation);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/EmployeeController.cs
using EmployeeManagement.Data;
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public EmployeeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Employee> employees = await _db.Employees
                .Include(e=>e.Designation)
                .Include(e=>e.PaymentRule)
                .Include(e=>e.WorkingHour)
                .ToListAsync();
            return View(employees);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var designations = await _db.Designation.ToListAsync();
            ViewBag.Designations = new SelectList(designations, "Id", "Name");

            var workingHours = await _db.WorkingHour.ToListAsync();
            ViewBag.WorkingHours = new SelectList(workingHours, "Id", "EmployeeMonthlyWorkingHour");

            var paymentRules = await _db.PaymentRule.ToListAsync();
            ViewBag.PaymentRules = new SelectList(paymentRules, "Id", "RuleName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _db.Employees.Add(employee);
                _db.SaveChanges();
                return RedirectToAction("Index"); // Replace "Index" with the appropriate action to redirect after successful employee creation
            }
            else
            {
                ViewBag.Designations = null;
                var designations = await _db.Designation.ToListAsync();
                ViewBag.Designations = new SelectList(designations, "Id", "Name");

                var workingHours = await _db.WorkingHour.ToListAsync();
                ViewBag.WorkingHours = new SelectList(workingHours, "Id", "EmployeeMonthlyWorkingHour");

                var paymentRules = await _db.PaymentRule.ToListAsync();
                ViewBag.PaymentRules = new SelectList(paymentRules, "Id", "RuleName");
                return View(employee);
            }
        }
        public async Task<IActionResult> Edit(int id)
        {
            Employee employee = await _db.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            var designations = await _db.Designation.ToListAsync();
            ViewBag.Designations = new SelectList(designations, "Id", "Name", employee.DesignationId);

            var workingHours = await _db.WorkingHour.ToListAsync();
            ViewBag.WorkingHours = new SelectList(workingHours, "Id", "EmployeeMonthlyWorkingHour", employee.WorkingHourId);

            var paymentRules = await _db.PaymentRule.ToListAsync();
            ViewBag.PaymentRules = new SelectList(paymentRules, "Id", "RuleName", employee.PaymentRuleId);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Load the associated entities from the database
                employee.Designation = await _db.Designation.FindAsync(employee.DesignationId);
                employee.WorkingHour = await _db.WorkingHour.FindAsync(employee.WorkingHourId);
                employee.PaymentRule = await _db.PaymentRule.FindAsync(employee.PaymentRuleId);

                _db.Entry(employee).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            var designations = await _db.Designation.ToListAsync();
            ViewBag.Designations = new SelectList(designations, "Id", "Name", employee.DesignationId);

            var workingHours = await _db.WorkingHour.ToListAsync();
            ViewBag.WorkingHours = new SelectList(workingHours, "Id", "EmployeeMonthlyWorkingHour", employee.WorkingHourId);

            var paymentRules = await _db.PaymentRule.ToListAsync();
            ViewBag.PaymentRules = new SelectList(paymentRules, "Id", "RuleName", employee.PaymentRuleId);

            return View(employee);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Employee employee = await _db.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            _db.Employees.Remove(employee);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/PaymentRuleController.cs
using EmployeeManagement.Data;
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Controllers
{
    public class PaymentRuleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PaymentRuleController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var paymentRules = await _context.PaymentRule.ToListAsync();
            return View(paymentRules);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PaymentRule paymentRule)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paymentRule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(paymentRule);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentRule = await _context.PaymentRule.FindAsync(id);
            if (paymentRule == null)
            {
                return NotFound();
            }
            return View(paymentRule);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PaymentRule paymentRule)
        {
            if (id != paymentRule.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(paymentRule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(paymentRule);
        }



        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var paymentRule = await _context.PaymentRule.FindAsync(id);
            if (paymentRule == null)
            {
                return NotFound();
            }

            _context.PaymentRule.Remove(paymentRule);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }



    }
}

Controllers/WorkingHourController.cs
using EmployeeManagement.Data;
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Controllers
{
    public class WorkingHourController : Controller
    {
        private readonly ApplicationDbContext _db;

        public WorkingHourController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var workingHours = await _db.WorkingHour.ToListAsync();
            return View(workingHours);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WorkingHour workingHour)
        {
            if (ModelState.IsValid)
            {
                _db.WorkingHour.Add(workingHour);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(workingHour);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var workingHour = await _db.WorkingHour.FindAsync(id);
            if (workingHour == null)
            {
                return NotFound();
            }
            return View(workingHour);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, WorkingHour workingHour)
        {
            if (id != workingHour.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Entry(workingHour).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(workingHour);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var workingHour = await _db.WorkingHour.FindAsync(id);
            if (workingHour == null)
            {
                return NotFound();
            }

            _db.WorkingHour.Remove(workingHour);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Designation" asp-action="Index">Designation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="WorkingHour" asp-action="Index">Working Hour</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="PaymentRule" asp-action="Index">Payment Rule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-light">
            &copy; 2023 EmployeeManagement
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>